config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  get 'collection/:category/:slug' => 'products#show', as: :product
  get 'collection/' => 'products#index', as: :products
  get 'collection/:category' => 'products#index', as: :category_products

  get 'blog' => 'blog_posts#index', as: :blog_posts
  get 'blog/:blog_post_slug' => 'blog_posts#show', as: :blog_post

  get 'contact-us' => 'contact#show', as: 'contact'
  resources :enquiries, only: [:new, :create]
  get 'enquiry/sent' => 'enquiries#thankyou', as: 'thankyou'

  resources :purchases, only: [:new, :create]
  get 'purchases/complete' => 'purchases#complete', as: 'complete'
  get 'purchases/express_checkout_complete' => 'purchases#express_checkout_create', as: 'express_checkout_complete'
  get 'purchases/price' => 'purchases#value', as: 'purchase_price'

  resource :basket, only: [:show, :create, :destroy]
  get 'basket/count' => 'baskets#count', as: 'basket_count'
  get 'basket/value' => 'baskets#value', as: 'basket_value'

  get 'shipping' => 'static#shipping', as:'shipping'
  get 'returns' => 'static#returns', as:'returns'
  get 'privacy' => 'static#privacy', as:'privacy'
  get 'terms' => 'static#terms', as:'terms'
  get 'about' => 'static#about', as:'about'

  resource :signup

  get 'status' => 'status#show', as:'status'

  get '*unmatched_route', :to => 'application#raise_not_found!' if Rails.env == 'production'
end

app/models/basket.rb
class Basket

  attr_accessor :line_items, :voucher_code

  def initialize(session)
    @session = session
    if @session[:products]
      @line_items = @session[:products].map{|data| BasketLineItem.new(data['product_slug'], data['size'], data['qty'])}
    else
      @session[:products] = []
      @line_items = []
    end
    @voucher_code = @session[:voucher_code] || nil
  end

  def clear!
    @session[:products] = []
    @session[:voucher_code] = nil
  end

  def add(product_slug, size)
    if current_item = @line_items.select{|line| line.product_slug == product_slug and line.size == size}.first
      item = current_item
      item.plus(1)
    else
      @line_items << BasketLineItem.new(product_slug, size, 1)
    end
    @session[:products] = @line_items.map{|item| item.to_hash}
  end

  def remove(product_slug, size)
    @line_items.delete_if do |li|
      if size.empty?
        li.product_slug == product_slug
      else
        li.product_slug == product_slug && li.size == size
      end
    end
    @session[:products] = @line_items.map{|item| item.to_hash}
  end

  def voucher_code=(code)
    @voucher_code = code
    @session[:voucher_code] = code
  end

  def voucher
    voucher = Voucher.find_by_code(@voucher_code)
  end

  def voucher_discount_amount
    return 0.00 unless voucher
    voucher.fixed_discount_amount_in_cent
  end

  def voucher_discount_in_dollars
    return 0.00 unless voucher
    voucher.discount_in_dollars
  end

  def total_in_dollars
    total/100.00
  end

  def total
    amount = line_items.inject(0) do |sum, item|
      sum += item.total_in_cents
      sum
    end
    amount - voucher_discount_amount
  end

  def count
    line_items.inject(0) do |sum, item|
      sum += item.qty
      sum
    end
  end

end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController

  include ActionView::Helpers::TextHelper
  include ActionView::Helpers::NumberHelper

  def show
    @basket = Basket.new(session)
  end

  def create
    @basket = Basket.new(session)
    @basket.add(params[:product], params[:size])
    redirect_to basket_path
  end

  def destroy
    @basket = Basket.new(session)
    @basket.remove(params[:product_slug], params[:size])
    redirect_to basket_path
  end

  def count
    @basket = Basket.new(session)
    response = pluralize(@basket.count, 'Item') if @basket.count > 0
    render json: {items: response}
  end

end

app/helpers/basket_helper.rb
module BasketHelper
  def delivery_options_for_select
    options_array = Purchase::DeliveryPrices.map do |country_code, price|
      [
        "Ship to #{ISO3166::Country[country_code]}: #{price_string(price)}",
        country_code
      ]
    end
    options_array.unshift(['Please select your delivery country', ''])
    options_array.push(["Other: #{price_string Purchase::DefaultDeliveryPrice}", 'other'])
    options_for_select(options_array)
  end

  def price_string(price)
    price > 0 ? "#{number_to_currency(price/100.00)} AUD" : "FREE"
  end
end

app/views/baskets/show.html.erb
<legend>Basket Summary</legend>
<% if @basket.line_items.size < 1 %>
  <p>Your cart is empty at the moment. <%= link_to 'Continue shopping', products_path %>
<% else %>
  <%= render partial: 'shared/error_notice' %>
  <span class='js-voucher-message'></span>
  <table class="table basket-summary basket_product_details">
    <tbody>
      <% @basket.line_items.each do |line_item| %>
        <% product = line_item.product %>
        <%= render partial: 'shared/basket_row', locals: {product: product, line_item: line_item,on_purchase: false} %>
      <% end %>
    </tbody>
  </table>
  <%= form_tag new_purchase_path, method: 'get' do |form| %>
    <table class="table basket-summary">
      <tbody>
        <tr>
          <td class='hidden-xs'></td>
          <td class='hidden-xs'></td>
          <td>Voucher Discount</td>
          <td class="js-voucher-discount"><%= number_to_currency @basket.voucher_discount_in_dollars %></td>
        </tr>
        <tr>
          <td class='hidden-xs'></td>
          <td class='hidden-xs'></td>
          <td>Delivery Price</td>
          <td>
            <div class="form-group <%= flash[:error] ? 'has-error' : ''%>">
              <%= select_tag 'country', delivery_options_for_select, class: 'js-delivery-select form-control' %>
            </div>

          </td>
        </tr>
        <tr>
          <td class='hidden-xs'></td>
          <td class='hidden-xs'></td>
          <td>Total Price</td>
          <td><strong class="js-total-price"><%= number_to_currency(@basket.total_in_dollars) %></strong></td>
        </tr>
      </tbody>
    </table>
    <div class="form-group form-inline pull-left">
      <legend>Apply a promo code</legend>
      <%= label_tag :voucher_code, "Please enter your promotional code/voucher" %>
      <%= text_field_tag :voucher_code, @basket.voucher_code, placeholder: 'Voucher Code', class: 'js-voucher-code form-control' %>
      <button class='btn btn-primary submit-button js-voucher-button' type='button'>Apply</button>
    </div>

    <div class="form-group text-right">
      <button class='btn btn-primary submit-button' type='submit'>CHECKOUT</button>
      <input class='btn submit-button' type='image' alt='Pay with Paypal' src="https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-medium.png" name='paypal_checkout'></button>
    </div>
  <% end %>
<% end %>

<%= javascript_tag do %>
  new Basket('<%= basket_value_path %>')
<% end %>