config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  get 'collection/:category/:slug' => 'products#show', as: :product
  get 'collection/' => 'products#index', as: :products
  get 'collection/:category' => 'products#index', as: :category_products

  get 'blog' => 'blog_posts#index', as: :blog_posts
  get 'blog/:blog_post_slug' => 'blog_posts#show', as: :blog_post

  get 'contact-us' => 'contact#show', as: 'contact'
  resources :enquiries, only: [:new, :create]
  get 'enquiry/sent' => 'enquiries#thankyou', as: 'thankyou'

  resources :purchases, only: [:new, :create]
  get 'purchases/complete' => 'purchases#complete', as: 'complete'
  get 'purchases/express_checkout_complete' => 'purchases#express_checkout_create', as: 'express_checkout_complete'
  get 'purchases/price' => 'purchases#value', as: 'purchase_price'

  resource :basket, only: [:show, :create, :destroy]
  get 'basket/count' => 'baskets#count', as: 'basket_count'
  get 'basket/value' => 'baskets#value', as: 'basket_value'

  get 'shipping' => 'static#shipping', as:'shipping'
  get 'returns' => 'static#returns', as:'returns'
  get 'privacy' => 'static#privacy', as:'privacy'
  get 'terms' => 'static#terms', as:'terms'
  get 'about' => 'static#about', as:'about'

  resource :signup

  get 'status' => 'status#show', as:'status'

  get '*unmatched_route', :to => 'application#raise_not_found!' if Rails.env == 'production'
end

app/models/blog_post.rb
class BlogPost <  ActiveRecord::Base
  has_many :blog_post_items
  belongs_to :author

  accepts_nested_attributes_for :blog_post_items
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @posts = BlogPost.where(publish: true).order('created_at DESC')
  end

  def show
    @post = BlogPost.find_by_slug(params[:blog_post_slug])

    set_sidebar_assets
  end
end

app/views/blog_posts/index.html.erb
<h1>#morethanbeautiful Blog</h1>

<div class="text-center">
  <% @posts.each do |post| %>
    <article>
      <%= link_to blog_post_path(post.slug) do %>
        <% if post.content.present? %>
          <%= image_tag("blog/#{post.slug}/#{post.slug}.png", class:'img-responsive') %>
        <% else %>
          <%=
            cl_image_tag(
              post.banner_image_ref,
              fetch_format: :auto,
              quality: 60,
              height: 600,
              width: 600,
              mobile_quality: 60,
              mobile_height: 500,
              mobile_width: 500,
              crop: :fit,
              class: 'img-responsive',
              alt: post.title
            )
          %>
        <% end %>
        <h2><%= post.title %></h2>
      <% end %>
    </article>
  <% end %>
</div>

app/views/blog_posts/show.html.erb
<% content_for :title, "#{@post.title} | Kaya Active Blog | #morethanbeautiful Blog " %>
<% content_for :description, "#{@post.title} | Kaya Active Blog | #morethanbeautiful Blog " %>
<% content_for :img_src do %><link rel="image_src" href="<%= cl_image_path(@post.banner_image_ref) %>" / ><% end %>

<div class="col-md-8">
  <article itemscope itemtype="http://schema.org/Article" role='article' id='blogPost'>
  <header>
    <h1 itemprop="name"><%= @post.title %></h1>
  </header>
  <div itemprop='articleBody' class='articleBody'>
    <% if @post.content.present? %>
      <%= raw(markdown_format(erb_compile(@post.content))) %>
    <% else %>
      <% @post.blog_post_items.order(:created_at).each do |item| %>
        <% if item.content_type == 'text' %>
          <%= raw(markdown_format(erb_compile(item.content))) %>
        <% elsif item.content_type == 'image' %>
          <%=
            cl_image_tag(
              item.reference,
              class: 'img-responsive pinable',
              fetch_format: :auto,
              quality: 60,
              height: 800,
              width: 800,
              mobile_quality: 70,
              mobile_height: 300,
              mobile_width: 300,
              crop: :fit,
              alt: item.content.present? ? item.content : @post.title
            )
          %>
        <% elsif item.content_type == 'youtube' %>
          <%= youtube_tag item.reference %>
        <% elsif item.content_type == 'product' %>
          <%= related_products item.reference.split(',') %>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <% if @post.author %>
    <div class="author">
      <%=
        cl_image_tag(
          @post.author.cloudinary_ref,
          fetch_format: :auto,
          quality: 100,
          height: 70,
          width: 70,
          mobile_quality: 100,
          mobile_height: 50,
          mobile_width: 50,
          crop: :lfill,
          gravity: :face,
          radius: :max

        )
      %>
      <div><%= @post.author.name %></div>
      <div><%= @post.author.description %></div>
    </div>
  <% end %>
  <div class="share">
    <h3>Share</h3>
    <ul>
      <li class="facebook"><a href="https://www.facebook.com/sharer/sharer.php?u=<%= URI::encode blog_post_url(@post.slug) %>" rel="nofollow" class="fa fa-facebook-square" target="_blank"><span class="text-hide">share on Facebook</span></a></li>

      <li class="twitter"><a href="https://twitter.com/home?status=<%= URI::encode blog_post_url(@post.slug) %>" rel="nofollow" class="fa fa-twitter" target="_blank"><span class="text-hide">share on twitter</span></a></li>

      <li class="pinterest"><a href="https://www.pinterest.com/pin/create/button/?url=<%= URI::encode blog_post_url(@post.slug) %>&media=<%= URI::encode cl_image_path(@post.banner_image_ref) %>" target="_blank" rel="nofollow" class="fa fa-pinterest"><span class="text-hide">share on Pinterest</span></a></li>

      <li class="googleplus"><a href="https://plus.google.com/share?url=<%= URI::encode blog_post_url(@post.slug) %>" rel="nofollow" class="fa fa-google-plus-square" target="_blank"><span class="text-hide">share on googleplus</span></a></li>
    <ul>
  </div>
</article>
</div>
<div class="col-md-4 sidebar">
  <%= render partial: 'shared/sidebar' %>
</div>