config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  get 'collection/:category/:slug' => 'products#show', as: :product
  get 'collection/' => 'products#index', as: :products
  get 'collection/:category' => 'products#index', as: :category_products

  get 'blog' => 'blog_posts#index', as: :blog_posts
  get 'blog/:blog_post_slug' => 'blog_posts#show', as: :blog_post

  get 'contact-us' => 'contact#show', as: 'contact'
  resources :enquiries, only: [:new, :create]
  get 'enquiry/sent' => 'enquiries#thankyou', as: 'thankyou'

  resources :purchases, only: [:new, :create]
  get 'purchases/complete' => 'purchases#complete', as: 'complete'
  get 'purchases/express_checkout_complete' => 'purchases#express_checkout_create', as: 'express_checkout_complete'
  get 'purchases/price' => 'purchases#value', as: 'purchase_price'

  resource :basket, only: [:show, :create, :destroy]
  get 'basket/count' => 'baskets#count', as: 'basket_count'
  get 'basket/value' => 'baskets#value', as: 'basket_value'

  get 'shipping' => 'static#shipping', as:'shipping'
  get 'returns' => 'static#returns', as:'returns'
  get 'privacy' => 'static#privacy', as:'privacy'
  get 'terms' => 'static#terms', as:'terms'
  get 'about' => 'static#about', as:'about'

  resource :signup

  get 'status' => 'status#show', as:'status'

  get '*unmatched_route', :to => 'application#raise_not_found!' if Rails.env == 'production'
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  include ActionView::Helpers::NumberHelper

  def new
    if params[:country].empty?
      redirect_to basket_path, flash: {error: "Please choose a delivery destination."}
      return
    end

    if params['paypal_checkout.x']
      paypal_checkout_new
    else
      site_checkout_new
    end
  end

  def site_checkout_new
    @basket = Basket.new(session)
    line_items = @basket.line_items.map{|bli| bli.to_line_item }
    @purchase = Purchase.new(line_items: line_items, country: params[:country])
    @purchase.voucher_code = params[:voucher_code] if params[:voucher_code]
  end

  def paypal_checkout_new
    @basket = Basket.new(session)
    line_items = @basket.line_items.map{|bli| bli.to_line_item }
    @purchase = Purchase.new(line_items: line_items, country: params[:country])
    @purchase.voucher_code = params[:voucher_code] if params[:voucher_code]

    items = @purchase.line_items.map do |l|
      {
        name: l.product.name,
        description: "#{l.product.name} size: #{l.size}",
        quantity: l.qty,
        amount: l.price
      }
    end
    if @purchase.voucher_code
      items << {
          name: "Voucher: #{@purchase.voucher_code}",
          description: "Discount voucher #{@purchase.voucher_code} for #{number_to_currency(@purchase.voucher_discount_in_dollars)}",
          quantity: 1,
          amount: -@purchase.voucher_discount_amount.to_i
      }
    end

    response = EXPRESS_GATEWAY.setup_purchase(@purchase.total,
      shipping: @purchase.delivery_price,
      subtotal: @purchase.line_item_total - @purchase.voucher_discount_amount.to_i,
      handling: 0,
      tax: 0,
      ip: request.remote_ip,
      return_url: express_checkout_complete_url,
      cancel_return_url: basket_url,
      currency: "AUD",
      allow_guest_checkout: true,
      items: items
    )
    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end

  def create
    basket = Basket.new(session)
    @purchase = Purchase.new(purchase_params)
    line_items = basket.line_items.map{|bli| bli.to_line_item }
    @purchase.line_items = line_items
    @purchase.voucher_code = basket.voucher_code

    unless @purchase.valid?
      render :new
      return
    end

    begin
      @purchase.pay!
      @purchase.save!
    rescue Stripe::CardError => e
      render :new
      return
    end

    session[:purchase_id] = @purchase.id
    basket.clear!
    PurchaseMailer.confirmation(@purchase).deliver
    redirect_to action: :complete
  end

  def express_checkout_create
    response = EXPRESS_GATEWAY.details_for(params['token'])

    @purchase = Purchase.new_from_paypal(params['token'], response, request.remote_ip)

    basket = Basket.new(session)
    line_items = basket.line_items.map{|bli| bli.to_line_item }
    @purchase.line_items = line_items
    @purchase.voucher_code = basket.voucher_code

    unless @purchase.express_checkout_pay!
      redirect_to basket_path
      return
    end

    @purchase.save!

    session[:purchase_id] = @purchase.id
    basket.clear!
    PurchaseMailer.confirmation(@purchase).deliver
    redirect_to action: :complete
  end

  def complete
    @purchase = Purchase.find(session[:purchase_id])
  end

  def purchase_params
    params.require(:purchase).permit(
      :name,
      :email_address,
      :name_on_card,
      :stripe_token,
      :email_address,
      :address_line_1,
      :address_line_2,
      :city,
      :state,
      :post_code,
      :country,
      :voucher_code
    )
  end

end

app/views/purchases/_credit_card.html.erb
<div class="alert alert-danger js-stripe-error" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">Error:</span>
  <span class="payment-errors"></span>
</div>


<%= form.input :name_on_card, placeholder: 'Name on Card' %>
<div class="form-group control-group string required purchase_card_number">
  <label class="string required control-label col-md-4 control-label" for="purchase_card_number">
    <abbr title="required">*</abbr> Card Number
  </label>
  <div class="col-md-4 controls">
    <input type="text" data-stripe="number" class="string required form-control input-m" placeholder="Card Number" id="purchase_card_number"/>
  </div>
</div>

<div class="form-group control-group string required purchase_cvc">
  <label class="string required control-label col-md-4 control-label" for="purchase_cvc">
    <abbr title="required">*</abbr> CVC
  </label>
  <div class="col-md-4 controls">
    <input type="text" data-stripe="cvc" class="string required form-control input-m" placeholder="CVC" id="purchase_cvc"/>
  </div>
</div>

<div class="form-group control-group string required purchase_expiration">
  <label class="string required control-label col-md-4 control-label" for="purchase_expiration">
    <abbr title="required">*</abbr> Expiration
  </label>
  <div class="col-md-4 controls expiration">
    <input type="text" maxlength="2" data-stripe="exp-month" class="string required form-control input-m" placeholder="MM"/>
    <input type="text" maxlength="4" data-stripe="exp-year" class="string required form-control input-m" placeholder="YYYY"/>
  </div>
</div>

app/views/purchases/_delivery_address.html.erb
<%= form.input :address_line_1, placeholder: 'Address Line 1' %>
<%= form.input :address_line_2, placeholder: 'Address Line 2' %>
<%= form.input :city, placeholder: 'City' %>
<%= form.input :state, placeholder: 'State' %>
<%= form.input :post_code, placeholder: 'Post Code' %>
<%= form.input :country, placeholder: 'Country' %>

app/views/purchases/complete.html.erb
<div class='confirmation'>
  <h1>Thank you for your order.</h1>

  <h2>Your order number is: <%= @purchase.code %></h2>

  <p>You will receive an email confirmation shortly at: <%= @purchase.email_address %></p>

  <p><%= link_to 'Continue Shopping', products_path, class: "btn btn-info" %></p>

</div>

<%= render partial: 'shared/google_conversion_tracking' %>

app/views/purchases/new.html.erb
<%= simple_form_for @purchase, html: {class: 'form-horizontal checkout'}, defaults: { label_html: {class: 'col-md-4 control-label'}, input_html: { class: 'form-control input-m' } } do |form| %>

  <% if @purchase.errors[:card].first %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      <%= @purchase.errors[:card].first %>
    </div>
  <% end %>

  <legend>Order Summary</legend>
  <table class="table order-summary">
    <tbody>
      <% @purchase.line_items.each do |line_item| %>
        <%= render partial: 'shared/basket_row', locals: {product: line_item.product, line_item: line_item, on_purchase: true} %>
      <% end %>
        <tr>
          <td></td>
          <td>Voucher Discount</td>
          <td>
            <strong class="js-voucher-discount">
              <%= @purchase.voucher ? number_to_currency(@purchase.voucher.discount_in_dollars) : "$0.00" %>
            </strong>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>Delivery Price</td>
          <td><strong class="js-delivery-price"><%= @purchase.delivery_price > 0 ? number_to_currency(@purchase.delivery_price/100.00) : "FREE" %></strong></td>
        </tr>
        <tr>
          <td></td>
          <td>Total Price</td>
          <td><strong class="js-total-price"><%= number_to_currency(@purchase.total_in_dollars) %></strong></td>
        </tr>
    </tbody>
  </table>

  <%= form_auth_field %>
  <%= hidden_field_tag :size, params[:size]  %>
      <legend>About You</legend>
      <%= form.input :name, placeholder: 'Name' %>
      <%= form.input :email_address, placeholder: 'Email Address' %>

      <legend>Delivery Address Details</legend>
      <%= render partial: 'delivery_address', locals: {form: form} %>

      <legend>Card Details</legend>
      <%= render partial: 'credit_card', locals: {form: form} %>

      <div class="buttons col-md-4"></div>
      <div class="buttons col-md-4">
        <button class='form-control btn btn-primary submit-button' type='submit'>Pay <span class="js-total-price"><%= number_to_currency(@purchase.total_in_dollars) %></span> »</button>
      </div>
      <div class="buttons col-md-4"></div>
<% end %>

<%= javascript_tag do %>
  new Checkout('<%= @purchase.total %>', '<%= purchase_price_path(format: :json) %>')
<% end %>