config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landing#index'

  get 'collection/:category/:slug' => 'products#show', as: :product
  get 'collection/' => 'products#index', as: :products
  get 'collection/:category' => 'products#index', as: :category_products

  get 'blog' => 'blog_posts#index', as: :blog_posts
  get 'blog/:blog_post_slug' => 'blog_posts#show', as: :blog_post

  get 'contact-us' => 'contact#show', as: 'contact'
  resources :enquiries, only: [:new, :create]
  get 'enquiry/sent' => 'enquiries#thankyou', as: 'thankyou'

  resources :purchases, only: [:new, :create]
  get 'purchases/complete' => 'purchases#complete', as: 'complete'
  get 'purchases/express_checkout_complete' => 'purchases#express_checkout_create', as: 'express_checkout_complete'
  get 'purchases/price' => 'purchases#value', as: 'purchase_price'

  resource :basket, only: [:show, :create, :destroy]
  get 'basket/count' => 'baskets#count', as: 'basket_count'
  get 'basket/value' => 'baskets#value', as: 'basket_value'

  get 'shipping' => 'static#shipping', as:'shipping'
  get 'returns' => 'static#returns', as:'returns'
  get 'privacy' => 'static#privacy', as:'privacy'
  get 'terms' => 'static#terms', as:'terms'
  get 'about' => 'static#about', as:'about'

  resource :signup

  get 'status' => 'status#show', as:'status'

  get '*unmatched_route', :to => 'application#raise_not_found!' if Rails.env == 'production'
end

app/views/shared/404.html.erb
<div class="text-center">
	<h1>404</h1>
	<p>Sorry, it looks like the page you're after doesn't exist.</p>
	<p><%= link_to "Go to the homepage", root_path %></p>
</div>

app/views/shared/_basket_row.html.erb
<tr>
  <td class='details'>
    <div class="row">
      <div class="col-xs-4">
        <%= cl_image_tag product.default_image.cloudinary_ref,
          alt: "#{product.name}",
          height: 150,
          width: 175,
          crop: :pad,
          mobile_height: 100,
          mobile_width: 80,
          fetch_format: :auto
        %>
      </div>
      <div class="col-xs-8">
        <p class='lead'><%= product.name %></p>
        <%= line_item.size %>
      </div>
    </div>
    <% unless on_purchase %>
      <div class='remove'>
        <%= form_tag basket_path, method: 'delete' do |form| %>
          <%= hidden_field_tag :product_slug, line_item.product.slug %>
          <%= hidden_field_tag :size, line_item.size %>
          <button type='submit' class="fa fa-times"></button>
        <% end %>
      </div>
    <% end %>
  </td>
  <td class='qty'><%= line_item.qty %></td>
  <td class='total'><%= number_to_currency(line_item.total_in_dollars) %></td>
  <% unless on_purchase %>
    <td class='hidden-xs'>
      <%= form_tag basket_path, method: 'delete' do |form| %>
        <%= hidden_field_tag :product_slug, line_item.product.slug %>
        <%= hidden_field_tag :size, line_item.size %>
        <button type='submit' class="fa fa-times"></button>
      <% end %>
    </td>
  <% end %>

</tr>

app/views/shared/_error_notice.html.erb
<% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class='col-md-4'>
      <h4>Shop</h4>
      <ul>
        <li><a href="<%= category_products_path(category:'leggings') %>">Leggings</a></li>
        <li><a href="<%= category_products_path(category:'tops') %>">Tops</a></li>
        <li><a href="<%= category_products_path(category:'yoga-mats') %>">Yoga Mats</a></li>
        <li><a href="<%= category_products_path(category:'bodysuits') %>">Bodysuits</a></li>
        <li><a href="<%= category_products_path(category:'belts') %>">Belts</a></li>
      </ul>
    </div>
    <div class='col-md-4'>
      <h4>Customer Service</h4>
      <ul>
        <li><%= link_to "Shipping", shipping_path %></li>
        <li><%= link_to "Returns", returns_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
        <li><%= link_to "Our Story", about_path %></li>
        <!--<li><%= link_to "Privacy Policy", privacy_path %></li>
        <li><%= link_to "Term and Conditions", terms_path %></li>-->
      </ul>
    </div>
    <div class='col-md-4'>
      <h4>Social</h4>
      <div class="row">
        <ul class="social share">
          <li class="facebook"><a href="https://www.facebook.com/kayaactive" target="_blank" class="fa fa-facebook-square"><span class="text-hide">Kaya Active on Facebook</span></a></li>
          <li class="instagram"><a href="http://instagram.com/kayaactive" target="_blank" class="fa fa-instagram"><span class="text-hide">Kaya Active on Instagram</span></a></li>
          <li class="pinterest"><a href="http://www.pinterest.com/kayaactive/" target="_blank" class="fa fa-pinterest-square"><span class="text-hide">Kaya Active on Pinterest</span></a></li>
        </ul>
      </div>
      <div id='signup' class="row">
        <%= form_for :signup, url: signup_path do |f| %>
          <p>Sign up here for Kaya's email updates</p>
          <%= f.text_field :email_address, placeholder: 'Email Updates' %>
          <%= f.button 'Sign up' %>
          <div class="alert alert-success" style="display:none" role="alert">
            Thank you, your email address has been saved
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container address">
    © <%= Time.now.year %> <a href="http://www.dharmabums.com.au">Kaya Active</a> ABN: 13348910186  |  All prices are in AUD.
    <br>
    <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
      <span itemprop="streetAddress">706/50 Clarence Street</span>,
      <span itemprop="city">Sydney</span>,
      <span itemprop="state">NSW</span>
      <span itemprop="postalcode">2000</span>
      <span itemprop="country">Australia</span>
    </span>
  </div>
</footer>

app/views/shared/_ga.html.erb
<% if Rails.env == 'production' %>
  <!-- GA -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-53348972-1', 'auto');
    ga('send', 'pageview');

  </script>
  <!-- /GA -->
<% end %>

app/views/shared/_google_conversion_tracking.html.erb
<!-- Google Code for track transactions Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 950428534;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "QNAhCIeJkVwQ9saZxQM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/950428534/?label=QNAhCIeJkVwQ9saZxQM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

app/views/shared/_google_remarketing.html.erb
<% if Rails.env == 'production' %>
<!-- Google Code for Remarketing Tag -->
<!--
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
-->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 950428534;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950428534/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<% end %>

app/views/shared/_head.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for :title %>Kaya Active | Womens premium inspirational activewear | Yoga, Crossfit, running and more</title>
<meta name="description" content="<%= content_for(:description) || "Kaya Active is the women's premium active wear retailer. Our range of high quality and inspiring sportswear is perfect for yoga, crossfit, pilates, running, and bikram. Be Active, be inspired and feel beautiful." %>" />
<meta name="keywords" content="leggings, yoga pants, yoga leggings, crossfit leggings, crossfit wear, printed leggings, brazilian leggings, patterned leggings, patterned tights, leggings from brazil, tights from brazil, colourful leggings" />

<link href="http://fonts.googleapis.com/css?family=Lato|Muli" rel="stylesheet" type="text/css">
<link rel="shortcut icon" href="<%= image_path "favicon.ico" %>" type="image/x-icon">
<link rel="icon" href="<%= image_path "favicon.ico" %>" type="image/x-icon">
<%= content_for :img_src %>

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
<meta name="p:domain_verify" content="d7fcd7d2a31534260b828b262b367ca8"/>
<meta name="google-site-verification" content="paX1FA8GgVqIFtxX7AL8VHpkWrsYkZSv1sVlwqdmyX8" />

app/views/shared/_lozenge.html.erb
<div class="thumbnail">
  <a href="<%= product_path(slug: product.slug, category: product.category.downcase) %>">
    <% if product.default_image %>
      <%= cl_image_tag product.default_image.cloudinary_ref,
                    alt: "#{product.name}",
                    height: 400,
                    width: 275,
                    crop: :pad,
                    mobile_width: 200,
                    mobile_height: 350,
                    fetch_format: :auto
      %>
    <% end %>
    <div class="caption text-center">
      <h3><%= product.name.titleize %></h3>
      <p class="price"><%= number_to_currency(product.price_in_dollars) if product.price_in_dollars.present?  %></p>
    </div>
  </a>
</div>

app/views/shared/_mobile_category_menu.html.erb
<ul class="nav nav-stacked visible-xs mobile-nav">
  <%= menu_list_item(nil, 'Summer Collection') %>
  <%= menu_list_item('leggings', 'Leggings') %>
  <%= menu_list_item('tops', 'Tops') %>
  <%= menu_list_item('yoga-mats', 'Yoga Mats') %>
  <%= menu_list_item('bodysuits', 'Bodysuits') %>
  <%= menu_list_item('belts', 'Belts') %>
  <li><%= link_to "Blog", blog_posts_path %></li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <ul class="navigation">
      <li class="hidden-xs"><%= link_to "Shop", products_path %></li>
      <li class="hidden-xs"><%= link_to "Our Story", about_path %></li>
      <% if homepage? %>
        <li><%= link_to image_tag('kaya_logo_white.png', alt: 'Kaya Active Logo', class: 'navbar-brand'), root_path %></li>
      <% else %>
        <li class="logo"><%= link_to image_tag('kaya_logo.png', alt: 'Kaya Active Logo', class: 'navbar-brand'), root_path %></li>
      <% end %>
      <li class="hidden-xs"><%= link_to "Blog", blog_posts_path %></li>
      <li class="hidden-xs"><%= link_to "Contact Us", contact_path %></li>
      <li class="basket">
        <%= link_to basket_path, class: 'fa fa-shopping-cart' do %>
          <span id="js-cart-item-count"></span</li>
        <% end %>
      </li>

    </ul>

    <div class="panel-group burger-menu visible-xs">
      <div class="panel">
        <div class="panel-heading" role="tab" id="headingOne">
          <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              <i class="fa fa-bars"></i>
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body">
            <ul class="nav nav-stacked visible-xs mobile-nav">
              <li><%= link_to "Shop", products_path %></li>
              <li><%= link_to "Our Story", about_path %></li>
              <li><%= link_to "Blog", blog_posts_path %></li>
              <li><%= link_to "Contact Us", contact_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= content_for :categories %>

</nav>

app/views/shared/_product_list.html.erb
<%
  unless defined?(split)
    split = 3
  end
%>

<div class="row">
  <% products.each do |product| %>
    <% next if product.nil? or product.images.first.nil? %>
    <div class="col-xs-6 col-sm-6 col-lg-<%= split %> col-md-<%= split %>">
      <%= render partial: 'shared/lozenge', locals: {product: product} %>
    </div>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<div class="section">
  <h4>Our Shop</h4>
  <%= render partial: 'shared/product_list', locals: {products: @products, split: 6} %>
  <p class="text-right"><%= link_to "Show more", category_products_path(category:'leggings') %></p>
</div>
<div class="section">
  <h4>Recent Articles</h4>
  <% @recent_articles.each_with_index do |post, index| %>
    <article>
      <%= link_to blog_post_path(post.slug) do %>
        <div class="row <%= 'last' if index == @recent_articles.size - 1 %>">
          <div class="col-md-3 col-xs-3">
            <%=
              cl_image_tag(
                post.banner_image_ref,
                fetch_format: :auto,
                quality: 100,
                height: 60,
                width: 60,
                crop: :fit,
                class: 'img-responsive',
                alt: post.title
              )
            %>
          </div>
          <div class="col-md-9 col-xs-9">
            <h5><%= post.title %></h5>
          </div>
        </div>
      <% end %>
    </article>
  <% end %>
</div>

app/views/shared/google_remarketing.html.erb
<% if Rails.env == 'production' %>
<!-- Google Code for Remarketing Tag -->
<!--
Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. See more information and instructions on how to setup the tag on: http://google.com/ads/remarketingsetup
-->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 950428534;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/950428534/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<% end %>